version: '3'

services:

  # backend Service with nestjs-express framework
  backend:
    build:
      context: "./backend"
      args:
       NODE_VERSION: ${NODE_VERSION}
    user: "${UID}:${GID}"
    volumes:
      - ./backend:/usr/src/app
      - ./backend/node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "5000:5000"
      # - "9229:9229" #debug address
    networks:
      - network
    environment:
      NODE_ENV: development
      MODE: DEV
      PORT: 3000
    env_file:
    - database.env
    command: "npm run start:dev"
    # command: "tail -f"
    depends_on:
      - postgres
  
  # frontend Service with vuejs framework
  frontend:
    build:
      context: "./frontend"
      args:
       NODE_VERSION: ${NODE_VERSION}
    user: "${UID}:${GID}"
    volumes:
      - ./frontend:/usr/src/app
      - ./frontend/node_modules:/usr/src/app/node_modules
      # - /usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
    ports:
      - "8080:8080"
      # - "5000:3000" #For json-server (development)
    networks:
      - network
    environment:
      NODE_ENV: development
      NAME: Julien
    command: "npm run serve"
    # command: "tail -f"
    depends_on:
      - postgres
  

  # PostgreSQL Service
  postgres:
    image: postgres:${POSTGRES_VERSION}
    networks:
      - network
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    container_name: ${POSTGRES_NAME}

  # Adminer Service
  adminer:
    image: adminer:${ADMINER_VERSION}
    networks:
      - network
    restart: on-failure
    ports:
      - "8000:8080"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: ${DB_HOST}
      ADMINER_DEFAULT_SERVER: ${DB_HOST}
      ADMINER_DEFAULT_DB_NAME: ${DB_NAME}
    volumes:
      - adminerdata:/var/www/html
    depends_on:
      - postgres
    # container_name: "${ADMINER_NAME}"

  # # Pgadmin Service
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - "8001:80"
  #   links:
  #     - "postgres"
  #   environment:
  #     PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
  #     PGADMIN_DEFAULT_EMAIL: j.nolleau88@gmail.com
  #   networks: 
  #     - backend
  #   depends_on:
  #     - postgres

  # Networks
networks:
  network:

#   # Volumes
volumes:
  adminerdata:
  # postgresdata:
