version: '3'

services:

  # Frontend Service with express framework
  frontend:
    build:
      context: "./nodejs"
      args:
       NODE_VERSION: ${NODE_VERSION}
    ports:
      - "8080:8080"
    working_dir: /usr/src/app
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/usr/src/app
      # - /usr/app/node_modules
    command: "node server.js"
    depends_on:
      - postgres
  

  # PostgreSQL Service
  postgres:
    image: postgres:${POSTGRES_VERSION}
    networks:
      - backend
      - frontend
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    container_name: ${POSTGRES_NAME}

  # Networks
networks:
  backend:
  frontend:

  # Volumes
# volumes:
  # postgredata:
