/* tslint:disable */
/* eslint-disable */
/**
 * ft_transcendence API
 * Because we are the best
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
    /**
     * 
     * @type {string}
     * @memberof CreateUserDto
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDto
     */
    surname: any;
}
